language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
    packages:
    - bash
    - curl
    - sudo
    - python-pip

install: true
before_script:
- sudo pip install httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80

script:
- bash mvnw

before_deploy:
- ./mvnw -Pdocs

env:
  global:
  - TERM=dumb
  - secure: BsNvMtpx11WM/1yFP1uBTKh7Y903xUcUxa/fSijIjGaixLTlpDBqVAOLbSjwE3AF50PWQenJc2LSFEz0GQ3h6RuEJbPqGmkAwndh+QL+tYsy4U/nGcfakILQbKH8HLGv+C1N5YQKds2Fc0SDNnjIHe5x+tWJPAG1gF+XjzPkaDC1dIJEgYkixlMXMzKb8CFZ35qDWG5xg86WPQN3VSKEVmyq1AqzNctP1P9vFXeD0Nin/IhcJYpc5an0EI2+HVGylAbBqTrMokgd6Nu3EaMBXAYqDc2wR0Lu4DgMQDC551Zb7vzoHfAvTFopojP0dRFKOE3bYafGAiPjwqg4Ac8Dg/uJR/mcHrVuej7WKlrGaF7UyIIB51y1lq31wn2GCx9n2+eCbTOQJ6dLu9JbfjbzIvtsXc9bT12qaZL6GgFo2P/g33sq+SVLDe07uWfdrNLuFbZAsMBpNlDCLqz/+jikVOwXMNsm/2ttSndds724ayMgb+hvWV6eg93PwyWz7/1GV/wcfBeEmJBV+qY4ntkeyMj9+CSI/Wv7WZ4hfVmSK+nirGwSXXeDrL/TW75ZnDATpUjx6aBJesRpIV8DLynPHAFxH0s4T2RWyXC+mv/f8h/WMz5ta9CPEadB+1TlBUJBLtDysOhuXaFoKArqr3KU+c0j0y31Bpft0rcBWu9K6TE=

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages

cache:
  directories:
  - $HOME/.m2
  - $HOME/.docker
